version: "3"

services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/ecommerce/:/var/www/ecommerce
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
    networks:
      - ecommerce-network

  ecommerce:
    build:
      context: apps/ecommerce
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: ecommerce
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ecommerce
      SERVICE_TAGS: dev
    working_dir: /var/www/ecommerce
    volumes:
      - ./apps/ecommerce/:/var/www/ecommerce
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ecommerce-network

  db:
    image: mysql:5.6
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: ecommerce_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - ecommerce-network
  
  redis:
    image: redis:4.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
